### ISSUE TITLE
Bug: TI and standard deviation miscalculated for BTS files starting from version v0.3-27

### ISSUE THREAD

**Issue by achilleas101** [ebranlard/pyDatView#186]
Dear @ebranlard,
I downloaded v.04 of pyDatView because I wanted to visualize the .bts file created by TurbSim using this input file ([TurbSim.txt](https://github.com/user-attachments/files/16141640/TurbSim.txt)), in which I forced TI to be 16% at 150m. Opening the .bts file with v0.4 and v0.3-7 gives different plots (this also happens for all the plots except u_[m/s])

From v0.4
![image1](https://github.com/ebranlard/pyDatView/assets/130864550/62239dbd-4d16-4c8c-9e77-8489cf47671f)
from v0.3-7
![image](https://github.com/ebranlard/pyDatView/assets/130864550/7369ea76-4f19-4743-9f91-1ce82d06f58b)

In the second plot as you can see at 150m we have TI=16%. So which version should?

Thank you for your help in advane!
Best regards,
Achilleas

**Comment by ebranlard** [comment]
Hi @achilleas101 
Thank you for pointing this out. There is indeed a bug that crept itself (related to averaging method we discussed in #185). 
There is a bit of a typo on the following line:
  https://github.com/ebranlard/pyDatView/blob/main/pydatview/io/turbsim_file.py#L357 
I used std of std instead of mean of std, which would be more appropriate. 

I'll push a fix for this shortly. 

Thanks again!

**Comment by ebranlard** [comment]
It should now be fixed in the latest dev release(v0.4-27). The profile will be smoother compared to v0.3-7 due to the averaging in the "y" direction.  Pease let me know if you find other problems. 

![image](https://github.com/user-attachments/assets/d77d1aa3-1ec2-48c4-959c-a0632880296d)
