### ISSUE TITLE
Panning becomes slow after increasing app window size

### ISSUE THREAD

**Issue by cdrtm** [ebranlard/pyDatView#98]
The app opens unmaximized by default, and panning works pretty smoothly.
But if I maximize the window, then try to pan, it becomes slow and unresponsive.
This happens even if I increase the window size without maximizing.
If I decrease the window size, I don't observe this issue.

Matplotlib doesn't give me this issue elsewhere, so I wonder if this has anything to do with using the wx backend.

I'm running this on Windows 10:
Python v3.6.8
matplotlib v3.3.4
wxPython v4.1.1

**Comment by ebranlard** [comment]
Interesting, I've never noticed this, but I believe I can see that the panning is smooth when the window is small, but lags otherwise. 
Since you are using windows, can you try with one of the "setup.exe" provided in release. I believe the behavior is the same as the one you observe. Let me know if it's worst or not.  The setup.exe uses slightly older versions: 
     python 3.6.0
     wxPython==4.0.3
     matplotlib==3.0.0

Actually, you made me realize that with my current matplotlib, the panning/zoom feature of pyDatView is broken.. 

I had to implement a subclass of NavigationToolbar2Wx in `GUIToolBox.py`. Unfortunately this class changes once in a while. We can try with the original class and see if the lag disapears..

**Comment by cdrtm** [comment]
I tested it on the setup.exe version and the same behavior is there. Doesn't seem to be neither worse nor better there.

**Comment by ebranlard** [comment]
I'll close this issue for now since it does seem to be related to the wx backend and I'm not sure how to fix it. Feel free to reopen it if you find a solution!

**Comment by ebranlard** [comment]
This indeed seems to be a wx backend issue, and I'm not sure how to fix it... I'll close this issue, but feel free to reopen it if you find something.
