### ISSUE TITLE
Ability to combine actions after applying a filter and "add" new dataset

### ISSUE THREAD

**Issue by cdrtm** [ebranlard/pyDatView#99]
Not sure if this issue has been brought up before:
- When you apply a filter, you only have the option of applying or plotting, both of which will reset on "Clear plot"
- This limitation means you can't apply a filter, then apply a sampler like "Every n" on top of it. The sampler will apply on the original data instead.
- We should be able to save the filtered plot, either as a new plot column or overwrite the original data. Adding a new table with filtered plot (similar to how resamplers work) is another option as well.

**Comment by ebranlard** [comment]
Sorry, I missed this issue somehow. I see what you mean. 

Combining actions is a bit dangerous since currently it's not easy to see which actions are active, but it should work (note: teh ssuccessive actions are applied in `plotdata _post_init`). I had a quick look, and the GUI should be able to combine "outliers" "filters", "resampling"  and "mask" but somehow it doesn't, so there might be a bug somewhere and the filter gets removed. 

As you mentioned, we should also add an "Add" button to the filter tool (note: `onAdd` calls `tab.applyResampling`. We should probably have instead something like `tab.applyAction` taking as argument `plotDataOptions`).

**Comment by ebranlard** [comment]
Now implemented. A small thing to be aware of is that the orders of these actions is currently not "remembered", and hard coded as: Mask -> Outliers -> Filter -> Sampler -> Binning. 

It wouldn't be too hard to remember the order of these actions and applying them in order within `plotdata.py`
I also think the user should be able to see somewhere on the GUI what kind of actions are currently applied and in which order. 

I'll post another feature request for that.
